spring:
  application:
    name: spring-boot-01
  mail:
    host: smtp.gmail.com
    password: abebebeso123
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: amdeberhans@gmail.com
  datasource:
    url: jdbc:mysql://localhost:3306/appointmentreservation
    username: root
    password: root@1234
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
server:
  port: 8010
